language: ruby
rvm:
  - 2.1.1
  - 1.9.3

services:
  - elasticsearch

notifications:
  email: false

sudo: true

before_install:
    - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.1.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.1.deb
    - "echo 'repo.path: /tmp/elasticsearch' >> /etc/elasticsearch/elasticsearch.yml"
