language: ruby
rvm:
  - 2.3.3

# Configure a specific version of Elasticsearch
# See: https://docs.travis-ci.com/user/database-setup/#Installing-ElasticSearch-on-trusty-container-based-infrastructure
install:
  - wget https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.3.5/elasticsearch-2.3.5.tar.gz
  - tar -xzf elasticsearch-2.3.5.tar.gz
  - ./elasticsearch-2.3.5/bin/elasticsearch &
script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - bundle install
  - bundle exec rake test

notifications:
  email: false

sudo: false
